<?php

namespace App\Containers\Vendor\Locationer\Providers;

use App\Containers\Vendor\Locationer\Locationer;
use App\Ship\Parents\Providers\MainProvider;

class LocationerServiceProvider extends MainProvider
{
    public function register(): void
    {
        parent::register();
        $this->app->singleton(Locationer::class);
    }

    public function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }
}
